[AccountManager]
Type = "GAE"
# Type = "unix"

[InstanceManager.GCP]
ProjectId = "google.com:cloud-android-jemoreira"
HostImage = "projects/google.com:cloud-android-jemoreira/global/images/sorama-demo-q2-final"

[Infra]
STUNServers = ["stun:stun.l.google.com:19302"]
